/**
 * Generated by Agitar build: AgitarOne Version 5.3.0.000022 (Build date: Jan 04, 2012) [5.3.0.000022]
 * JDK Version: 1.6.0_14
 *
 * Generated on 29 Jul, 2013 2:34:01 PM
 * Time to generate: 00:17.570 seconds
 *
 */

package com.huawei.unibi.molap.datastorage.store.compression.type;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import com.huawei.iweb.platform.logging.LogService;
import com.huawei.unibi.molap.datastorage.store.compression.Compressor;
import com.huawei.unibi.molap.datastorage.store.compression.ValueCompressionUtil;
import com.huawei.unibi.molap.datastorage.store.compression.ValueCompressonHolder;
import com.huawei.unibi.molap.util.MolapCoreLogEvent;
import java.nio.ByteBuffer;

public class UnCompressNonDecimalDefaultAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return UnCompressNonDecimalDefault.class;
    }
    
    public void testConstructor() throws Throwable {
        new UnCompressNonDecimalDefault();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testCompressWithAggressiveMocks() throws Throwable {
        storeStaticField(UnCompressNonDecimalDefault.class, "doubleCompressor");
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = (UnCompressNonDecimalDefault) Mockingbird.getProxyObject(UnCompressNonDecimalDefault.class, true);
        double[] doubles = new double[0];
        Mockingbird.enterRecordingMode();
        Mockingbird.replaceObjectForRecording(UnCompressNonDecimalByte.class, "<init>()", new UnCompressNonDecimalByte());
        Compressor compressor = (Compressor) Mockingbird.getProxyObject(Compressor.class);
        byte[] bytes = new byte[0];
        Mockingbird.enterNormalMode();
        unCompressNonDecimalDefault.setValue(doubles);
        setPrivateField(UnCompressNonDecimalDefault.class, "doubleCompressor", compressor);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(compressor.compress(doubles), bytes);
        Mockingbird.enterTestMode(UnCompressNonDecimalDefault.class);
        ValueCompressonHolder.UnCompressValue result = unCompressNonDecimalDefault.compress();
        assertEquals("result.getBackArrayData().length", 0, result.getBackArrayData().length);
        assertNotNull("unCompressNonDecimalDefaultUnCompressNonDecimalDefault.doubleCompressor", getPrivateField(UnCompressNonDecimalDefault.class, "doubleCompressor"));
    }
    
    public void testGetBackArrayData() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        double[] value = new double[0];
        unCompressNonDecimalDefault.setValue(value);
        byte[] result = unCompressNonDecimalDefault.getBackArrayData();
        assertEquals("result.length", 0, result.length);
    }
    
    public void testGetBackArrayData1() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        double[] value = new double[3];
        unCompressNonDecimalDefault.setValue(value);
        byte[] result = unCompressNonDecimalDefault.getBackArrayData();
        assertEquals("result.length", 24, result.length);
        assertEquals("result[0]", (byte)0, result[0]);
    }
    
    public void testGetCompressorObject() throws Throwable {
        UnCompressNonDecimalByte result = (UnCompressNonDecimalByte) new UnCompressNonDecimalDefault().getCompressorObject();
        assertNull("result.getBackArrayData()", result.getBackArrayData());
    }
    
    public void testGetNew() throws Throwable {
        UnCompressNonDecimalDefault result = (UnCompressNonDecimalDefault) new UnCompressNonDecimalDefault().getNew();
        assertNotNull("result", result);
    }
    
    public void testGetNewWithAggressiveMocks() throws Throwable {
        storeStaticField(MolapCoreLogEvent.class, "UNIBI_MOLAPCORE_MSG");
        storeStaticField(UnCompressNonDecimalDefault.class, "LOGGER");
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = (UnCompressNonDecimalDefault) Mockingbird.getProxyObject(UnCompressNonDecimalDefault.class, true);
        CloneNotSupportedException cloneNotSupportedException = (CloneNotSupportedException) Mockingbird.getProxyObject(CloneNotSupportedException.class);
        LogService logService = (LogService) Mockingbird.getProxyObject(LogService.class);
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(false, unCompressNonDecimalDefault, "clone", "()java.lang.Object", new Object[] {}, cloneNotSupportedException, 1);
        setPrivateField(UnCompressNonDecimalDefault.class, "LOGGER", logService);
        setPrivateField(MolapCoreLogEvent.class, "UNIBI_MOLAPCORE_MSG", null);
        Mockingbird.setReturnValue(false, cloneNotSupportedException, "getMessage", "()java.lang.String", new Object[] {}, "", 1);
        Mockingbird.setReturnValue(false, logService, "error", "(com.huawei.iweb.platform.logging.LogEvent,java.lang.Throwable,java.lang.Object[])void", null, 1);
        Mockingbird.enterTestMode(UnCompressNonDecimalDefault.class);
        ValueCompressonHolder.UnCompressValue result = unCompressNonDecimalDefault.getNew();
        assertNull("result", result);
    }
    
    public void testGetValue() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        double[] value = new double[3];
        unCompressNonDecimalDefault.setValue(value);
        double result = unCompressNonDecimalDefault.getValue(0, 100, 100.0);
        assertEquals("result", 0.0, result, 1.0E-6);
    }
    
    public void testGetValue1() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        double[] value = new double[1];
        value[0] = 22.03406524658203;
        unCompressNonDecimalDefault.setValue(value);
        double result = unCompressNonDecimalDefault.getValue(0, -1, 100.0);
        assertEquals("result", 220.3406524658203, result, 1.0E-6);
    }
    
    public void testSetValue() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        double[] value = new double[0];
        unCompressNonDecimalDefault.setValue(value);
        assertEquals("unCompressNonDecimalDefault.getBackArrayData().length", 0, unCompressNonDecimalDefault.getBackArrayData().length);
    }
    
    public void testSetValueInBytes() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        byte[] value = new byte[0];
        unCompressNonDecimalDefault.setValueInBytes(value);
        assertEquals("unCompressNonDecimalDefault.getBackArrayData().length", 0, unCompressNonDecimalDefault.getBackArrayData().length);
    }
    
    public void testUncompress() throws Throwable {
        ValueCompressonHolder.UnCompressValue result = new UnCompressNonDecimalDefault().uncompress(ValueCompressionUtil.DataType.DATA_SHORT);
        assertNull("result", result);
    }
    
    public void testGetBackArrayDataThrowsNullPointerException() throws Throwable {
        try {
            ((UnCompressNonDecimalDefault) new UnCompressNonDecimalDefault().getNew()).getBackArrayData();
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ValueCompressionUtil.class, ex);
        }
    }
    
    public void testGetValueThrowsArrayIndexOutOfBoundsException() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        double[] value = new double[0];
        unCompressNonDecimalDefault.setValue(value);
        try {
            unCompressNonDecimalDefault.getValue(100, 1000, 100.0);
            fail("Expected ArrayIndexOutOfBoundsException to be thrown");
        } catch (ArrayIndexOutOfBoundsException ex) {
            assertEquals("ex.getMessage()", "100", ex.getMessage());
            assertThrownBy(UnCompressNonDecimalDefault.class, ex);
        }
    }
    
    public void testGetValueThrowsNullPointerException() throws Throwable {
        try {
            new UnCompressNonDecimalDefault().getValue(100, 1000, 100.0);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(UnCompressNonDecimalDefault.class, ex);
        }
    }
    
    public void testSetValueInBytesThrowsNullPointerException() throws Throwable {
        UnCompressNonDecimalDefault unCompressNonDecimalDefault = new UnCompressNonDecimalDefault();
        try {
            unCompressNonDecimalDefault.setValueInBytes((byte[]) null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ByteBuffer.class, ex);
            assertNull("unCompressNonDecimalDefault.value", getPrivateField(unCompressNonDecimalDefault, "value"));
        }
    }
}

