/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/**
 * Generated by Agitar build: AgitarOne Version 5.3.0.000022 (Build date: Jan 04, 2012) [5.3.0.000022]
 * JDK Version: 1.6.0_14
 *
 * Generated on 29 Jul, 2013 2:34:42 PM
 * Time to generate: 00:16.742 seconds
 *
 */

package com.huawei.unibi.molap.datastorage.store.compression.type;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import com.huawei.iweb.platform.logging.LogService;
import com.huawei.unibi.molap.datastorage.store.compression.Compressor;
import com.huawei.unibi.molap.datastorage.store.compression.ValueCompressionUtil;
import com.huawei.unibi.molap.datastorage.store.compression.ValueCompressonHolder;
import com.huawei.unibi.molap.util.MolapCoreLogEvent;
import java.nio.ByteBuffer;

public class UnCompressNonDecimalMaxMinFloatAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return UnCompressNonDecimalMaxMinFloat.class;
    }
    
    public void testConstructor() throws Throwable {
        new UnCompressNonDecimalMaxMinFloat();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testCompressWithAggressiveMocks() throws Throwable {
        storeStaticField(UnCompressNonDecimalMaxMinFloat.class, "floatCompressor");
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = (UnCompressNonDecimalMaxMinFloat) Mockingbird.getProxyObject(UnCompressNonDecimalMaxMinFloat.class, true);
        float[] floats = new float[0];
        Mockingbird.enterRecordingMode();
        Mockingbird.replaceObjectForRecording(UnCompressNonDecimalMaxMinByte.class, "<init>()", new UnCompressNonDecimalMaxMinByte());
        Compressor compressor = (Compressor) Mockingbird.getProxyObject(Compressor.class);
        byte[] bytes = new byte[0];
        Mockingbird.enterNormalMode();
        unCompressNonDecimalMaxMinFloat.setValue(floats);
        setPrivateField(UnCompressNonDecimalMaxMinFloat.class, "floatCompressor", compressor);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(compressor.compress(floats), bytes);
        Mockingbird.enterTestMode(UnCompressNonDecimalMaxMinFloat.class);
        ValueCompressonHolder.UnCompressValue result = unCompressNonDecimalMaxMinFloat.compress();
        assertEquals("result.getBackArrayData().length", 0, result.getBackArrayData().length);
        assertNotNull("unCompressNonDecimalMaxMinFloatUnCompressNonDecimalMaxMinFloat.floatCompressor", getPrivateField(UnCompressNonDecimalMaxMinFloat.class, "floatCompressor"));
    }
    
    public void testGetBackArrayData() throws Throwable {
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = new UnCompressNonDecimalMaxMinFloat();
        float[] value = new float[0];
        unCompressNonDecimalMaxMinFloat.setValue(value);
        byte[] result = unCompressNonDecimalMaxMinFloat.getBackArrayData();
        assertEquals("result.length", 0, result.length);
    }
    
    public void testGetBackArrayData1() throws Throwable {
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = new UnCompressNonDecimalMaxMinFloat();
        float[] value = new float[2];
        unCompressNonDecimalMaxMinFloat.setValue(value);
        byte[] result = unCompressNonDecimalMaxMinFloat.getBackArrayData();
        assertEquals("result.length", 8, result.length);
        assertEquals("result[0]", (byte)0, result[0]);
    }
    
    public void testGetCompressorObject() throws Throwable {
        UnCompressNonDecimalMaxMinByte result = (UnCompressNonDecimalMaxMinByte) new UnCompressNonDecimalMaxMinFloat().getCompressorObject();
        assertNull("result.getBackArrayData()", result.getBackArrayData());
    }
    
    public void testGetNew() throws Throwable {
        UnCompressNonDecimalMaxMinFloat result = (UnCompressNonDecimalMaxMinFloat) new UnCompressNonDecimalMaxMinFloat().getNew();
        assertNotNull("result", result);
    }
    
    public void testGetNewWithAggressiveMocks() throws Throwable {
        storeStaticField(UnCompressNonDecimalMaxMinFloat.class, "LOGGER");
        storeStaticField(MolapCoreLogEvent.class, "UNIBI_MOLAPCORE_MSG");
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = (UnCompressNonDecimalMaxMinFloat) Mockingbird.getProxyObject(UnCompressNonDecimalMaxMinFloat.class, true);
        CloneNotSupportedException cloneNotSupportedException = (CloneNotSupportedException) Mockingbird.getProxyObject(CloneNotSupportedException.class);
        LogService logService = (LogService) Mockingbird.getProxyObject(LogService.class);
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(false, unCompressNonDecimalMaxMinFloat, "clone", "()java.lang.Object", new Object[] {}, cloneNotSupportedException, 1);
        setPrivateField(UnCompressNonDecimalMaxMinFloat.class, "LOGGER", logService);
        setPrivateField(MolapCoreLogEvent.class, "UNIBI_MOLAPCORE_MSG", null);
        Mockingbird.setReturnValue(false, cloneNotSupportedException, "getMessage", "()java.lang.String", new Object[] {}, "", 1);
        Mockingbird.setReturnValue(false, logService, "error", "(com.huawei.iweb.platform.logging.LogEvent,java.lang.Throwable,java.lang.Object[])void", null, 1);
        Mockingbird.enterTestMode(UnCompressNonDecimalMaxMinFloat.class);
        ValueCompressonHolder.UnCompressValue result = unCompressNonDecimalMaxMinFloat.getNew();
        assertNull("result", result);
    }
    
    public void testGetValue() throws Throwable {
        UnCompressNonDecimalMaxMinFloat new2 = (UnCompressNonDecimalMaxMinFloat) new UnCompressNonDecimalMaxMinFloat().getNew();
        float[] value = new float[3];
        new2.setValue(value);
        double result = new2.getValue(0, 100, 100.0);
        assertEquals("result", 1.0E-98, result, 1.0E-6);
    }
    
    public void testGetValue1() throws Throwable {
        float[] value = new float[3];
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = new UnCompressNonDecimalMaxMinFloat();
        unCompressNonDecimalMaxMinFloat.setValue(value);
        double result = unCompressNonDecimalMaxMinFloat.getValue(0, -1, 100.0);
        assertEquals("result", 1000.0, result, 1.0E-6);
    }
    
    public void testSetValue() throws Throwable {
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = new UnCompressNonDecimalMaxMinFloat();
        float[] value = new float[0];
        unCompressNonDecimalMaxMinFloat.setValue(value);
        assertEquals("unCompressNonDecimalMaxMinFloat.getBackArrayData().length", 0, unCompressNonDecimalMaxMinFloat.getBackArrayData().length);
    }
    
    public void testSetValueInBytes() throws Throwable {
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = new UnCompressNonDecimalMaxMinFloat();
        byte[] value = new byte[1];
        unCompressNonDecimalMaxMinFloat.setValueInBytes(value);
        assertEquals("unCompressNonDecimalMaxMinFloat.getBackArrayData().length", 0, unCompressNonDecimalMaxMinFloat.getBackArrayData().length);
    }
    
    public void testUncompress() throws Throwable {
        ValueCompressonHolder.UnCompressValue result = new UnCompressNonDecimalMaxMinFloat().uncompress(ValueCompressionUtil.DataType.DATA_SHORT);
        assertNull("result", result);
    }
    
    public void testGetBackArrayDataThrowsNullPointerException() throws Throwable {
        UnCompressNonDecimalMaxMinFloat new2 = (UnCompressNonDecimalMaxMinFloat) new UnCompressNonDecimalMaxMinFloat().getNew();
        new2.setValue((float[]) null);
        try {
            new2.getBackArrayData();
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ValueCompressionUtil.class, ex);
        }
    }
    
    public void testGetValueThrowsArrayIndexOutOfBoundsException() throws Throwable {
        float[] value = new float[3];
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = new UnCompressNonDecimalMaxMinFloat();
        unCompressNonDecimalMaxMinFloat.setValue(value);
        try {
            unCompressNonDecimalMaxMinFloat.getValue(100, 1000, 100.0);
            fail("Expected ArrayIndexOutOfBoundsException to be thrown");
        } catch (ArrayIndexOutOfBoundsException ex) {
            assertEquals("ex.getMessage()", "100", ex.getMessage());
            assertThrownBy(UnCompressNonDecimalMaxMinFloat.class, ex);
        }
    }
    
    public void testGetValueThrowsNullPointerException() throws Throwable {
        try {
            new UnCompressNonDecimalMaxMinFloat().getValue(100, 1000, 100.0);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(UnCompressNonDecimalMaxMinFloat.class, ex);
        }
    }
    
    public void testSetValueInBytesThrowsNullPointerException() throws Throwable {
        UnCompressNonDecimalMaxMinFloat unCompressNonDecimalMaxMinFloat = new UnCompressNonDecimalMaxMinFloat();
        try {
            unCompressNonDecimalMaxMinFloat.setValueInBytes((byte[]) null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ByteBuffer.class, ex);
            assertNull("unCompressNonDecimalMaxMinFloat.value", getPrivateField(unCompressNonDecimalMaxMinFloat, "value"));
        }
    }
}

