/**
 * Generated by Agitar build: AgitarOne Version 5.3.0.000022 (Build date: Jan 04, 2012) [5.3.0.000022]
 * JDK Version: 1.6.0_14
 *
 * Generated on 29 Jul, 2013 2:35:52 PM
 * Time to generate: 00:17.555 seconds
 *
 */

package com.huawei.unibi.molap.datastorage.store.compression.type;

import com.agitar.lib.junit.AgitarTestCase;
import com.agitar.lib.mockingbird.Mockingbird;
import com.huawei.iweb.platform.logging.LogService;
import com.huawei.unibi.molap.datastorage.store.compression.Compressor;
import com.huawei.unibi.molap.datastorage.store.compression.ValueCompressionUtil;
import com.huawei.unibi.molap.datastorage.store.compression.ValueCompressonHolder;
import com.huawei.unibi.molap.util.MolapCoreLogEvent;
import java.nio.ByteBuffer;

public class UnCompressNoneShortAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return UnCompressNoneShort.class;
    }
    
    public void testConstructor() throws Throwable {
        new UnCompressNoneShort();
        assertTrue("Test call resulted in expected outcome", true);
    }
    
    public void testCompressWithAggressiveMocks() throws Throwable {
        storeStaticField(UnCompressNoneShort.class, "shortCompressor");
        UnCompressNoneShort unCompressNoneShort = (UnCompressNoneShort) Mockingbird.getProxyObject(UnCompressNoneShort.class, true);
        short[] shorts = new short[0];
        Mockingbird.enterRecordingMode();
        Mockingbird.replaceObjectForRecording(UnCompressNoneByte.class, "<init>()", new UnCompressNoneByte());
        Compressor compressor = (Compressor) Mockingbird.getProxyObject(Compressor.class);
        byte[] bytes = new byte[0];
        Mockingbird.enterNormalMode();
        unCompressNoneShort.setValue(shorts);
        setPrivateField(UnCompressNoneShort.class, "shortCompressor", compressor);
        Mockingbird.enterRecordingMode();
        Mockingbird.setReturnValue(compressor.compress(shorts), bytes);
        Mockingbird.enterTestMode(UnCompressNoneShort.class);
        ValueCompressonHolder.UnCompressValue result = unCompressNoneShort.compress();
        assertEquals("result.getBackArrayData().length", 0, result.getBackArrayData().length);
        assertNotNull("unCompressNoneShortUnCompressNoneShort.shortCompressor", getPrivateField(UnCompressNoneShort.class, "shortCompressor"));
    }
    
    public void testGetBackArrayData() throws Throwable {
        short[] shortValue = new short[3];
        UnCompressNoneShort unCompressNoneShort = new UnCompressNoneShort();
        unCompressNoneShort.setValue(shortValue);
        byte[] result = unCompressNoneShort.getBackArrayData();
        assertEquals("result.length", 6, result.length);
        assertEquals("result[0]", (byte)0, result[0]);
    }
    
    public void testGetBackArrayData1() throws Throwable {
        short[] shortValue = new short[0];
        UnCompressNoneShort unCompressNoneShort = new UnCompressNoneShort();
        unCompressNoneShort.setValue(shortValue);
        byte[] result = unCompressNoneShort.getBackArrayData();
        assertEquals("result.length", 0, result.length);
    }
    
    public void testGetCompressorObject() throws Throwable {
        UnCompressNoneByte result = (UnCompressNoneByte) new UnCompressNoneShort().getCompressorObject();
        assertNull("result.getBackArrayData()", result.getBackArrayData());
    }
    
    public void testGetNew() throws Throwable {
        UnCompressNoneShort result = (UnCompressNoneShort) new UnCompressNoneShort().getNew();
        assertNotNull("result", result);
    }
    
    public void testGetNewWithAggressiveMocks() throws Throwable {
        storeStaticField(UnCompressNoneShort.class, "LOGGER");
        storeStaticField(MolapCoreLogEvent.class, "UNIBI_MOLAPCORE_MSG");
        UnCompressNoneShort unCompressNoneShort = (UnCompressNoneShort) Mockingbird.getProxyObject(UnCompressNoneShort.class, true);
        CloneNotSupportedException cloneNotSupportedException = (CloneNotSupportedException) Mockingbird.getProxyObject(CloneNotSupportedException.class);
        LogService logService = (LogService) Mockingbird.getProxyObject(LogService.class);
        Mockingbird.enterRecordingMode();
        Mockingbird.setException(false, unCompressNoneShort, "clone", "()java.lang.Object", new Object[] {}, cloneNotSupportedException, 1);
        setPrivateField(UnCompressNoneShort.class, "LOGGER", logService);
        setPrivateField(MolapCoreLogEvent.class, "UNIBI_MOLAPCORE_MSG", null);
        Mockingbird.setReturnValue(false, cloneNotSupportedException, "getMessage", "()java.lang.String", new Object[] {}, "", 1);
        Mockingbird.setReturnValue(false, logService, "error", "(com.huawei.iweb.platform.logging.LogEvent,java.lang.Throwable,java.lang.Object[])void", null, 1);
        Mockingbird.enterTestMode(UnCompressNoneShort.class);
        ValueCompressonHolder.UnCompressValue result = unCompressNoneShort.getNew();
        assertNull("result", result);
    }
    
    public void testGetValue() throws Throwable {
        UnCompressNoneShort new2 = (UnCompressNoneShort) ((UnCompressNoneShort) new UnCompressNoneShort().getNew()).getNew();
        byte[] value = new byte[3];
        new2.setValueInBytes(value);
        double result = new2.getValue(0, 100, 100.0);
        assertEquals("result", 0.0, result, 1.0E-6);
    }
    
    public void testGetValue1() throws Throwable {
        UnCompressNoneShort unCompressNoneShort = new UnCompressNoneShort();
        short[] shortValue = new short[4];
        shortValue[0] = (short)-1;
        unCompressNoneShort.setValue(shortValue);
        double result = unCompressNoneShort.getValue(0, 100, 100.0);
        assertEquals("result", -1.0, result, 1.0E-6);
    }
    
    public void testSetValue() throws Throwable {
        short[] shortValue = new short[0];
        UnCompressNoneShort unCompressNoneShort = new UnCompressNoneShort();
        unCompressNoneShort.setValue(shortValue);
        assertEquals("unCompressNoneShort.getBackArrayData().length", 0, unCompressNoneShort.getBackArrayData().length);
    }
    
    public void testSetValueInBytes() throws Throwable {
        UnCompressNoneShort unCompressNoneShort = new UnCompressNoneShort();
        byte[] value = new byte[0];
        unCompressNoneShort.setValueInBytes(value);
        assertEquals("unCompressNoneShort.getBackArrayData().length", 0, unCompressNoneShort.getBackArrayData().length);
    }
    
    public void testUncompress() throws Throwable {
        ValueCompressonHolder.UnCompressValue result = new UnCompressNoneShort().uncompress(ValueCompressionUtil.DataType.DATA_LONG);
        assertNull("result", result);
    }
    
    public void testGetBackArrayDataThrowsNullPointerException() throws Throwable {
        try {
            new UnCompressNoneShort().getBackArrayData();
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ValueCompressionUtil.class, ex);
        }
    }
    
    public void testGetValueThrowsArrayIndexOutOfBoundsException() throws Throwable {
        short[] shortValue = new short[1];
        UnCompressNoneShort unCompressNoneShort = new UnCompressNoneShort();
        unCompressNoneShort.setValue(shortValue);
        try {
            unCompressNoneShort.getValue(100, 1000, 100.0);
            fail("Expected ArrayIndexOutOfBoundsException to be thrown");
        } catch (ArrayIndexOutOfBoundsException ex) {
            assertEquals("ex.getMessage()", "100", ex.getMessage());
            assertThrownBy(UnCompressNoneShort.class, ex);
        }
    }
    
    public void testGetValueThrowsNullPointerException() throws Throwable {
        UnCompressNoneShort new2 = (UnCompressNoneShort) new UnCompressNoneShort().getNew();
        new2.setValue((short[]) null);
        try {
            new2.getValue(100, 1000, 100.0);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(UnCompressNoneShort.class, ex);
        }
    }
    
    public void testSetValueInBytesThrowsNullPointerException() throws Throwable {
        UnCompressNoneShort unCompressNoneShort = new UnCompressNoneShort();
        try {
            unCompressNoneShort.setValueInBytes((byte[]) null);
            fail("Expected NullPointerException to be thrown");
        } catch (NullPointerException ex) {
            assertNull("ex.getMessage()", ex.getMessage());
            assertThrownBy(ByteBuffer.class, ex);
            assertNull("unCompressNoneShort.shortValue", getPrivateField(unCompressNoneShort, "shortValue"));
        }
    }
}

