/**
 * Generated by Agitar build: AgitarOne Version 5.3.0.000022 (Build date: Jan 04, 2012) [5.3.0.000022]
 * JDK Version: 1.6.0_14
 *
 * Generated on Jul 31, 2013 6:23:26 PM
 * Time to generate: 00:16.519 seconds
 *
 */

package com.huawei.unibi.molap.merger.exeception;

import com.agitar.lib.junit.AgitarTestCase;
import java.util.Locale;

public class SliceMergerExceptionAgitarTest extends AgitarTestCase {
    
    public Class getTargetClass()  {
        return SliceMergerException.class;
    }
    
    public void testConstructor() throws Throwable {
        SliceMergerException sliceMergerException = new SliceMergerException("testSliceMergerExceptionMsg");
        assertEquals("sliceMergerException.getMessage()", "testSliceMergerExceptionMsg", sliceMergerException.getMessage());
        assertEquals("sliceMergerException.getMessage()", "testSliceMergerExceptionMsg", sliceMergerException.getMessage());
    }
    
    public void testConstructor1() throws Throwable {
        Throwable t = new IllegalMonitorStateException();
        SliceMergerException sliceMergerException = new SliceMergerException("testSliceMergerExceptionMsg", t);
        assertEquals("sliceMergerException.getMessage()", "testSliceMergerExceptionMsg", sliceMergerException.getMessage());
        assertSame("sliceMergerException.getCause()", t, sliceMergerException.getCause());
        assertEquals("sliceMergerException.getMessage()", "testSliceMergerExceptionMsg", sliceMergerException.getMessage());
    }
    
    public void testGetLocalizedMessage() throws Throwable {
        String result = new SliceMergerException("testSliceMergerExceptionMsg").getLocalizedMessage();
        assertEquals("result", "testSliceMergerExceptionMsg", result);
    }
    
    public void testGetLocalizedMessage1() throws Throwable {
        String result = new SliceMergerException(null).getLocalizedMessage();
        assertNull("result", result);
    }
    
    public void testGetLocalizedMessage2() throws Throwable {
        String result = new SliceMergerException("testSliceMergerExceptionMsg").getLocalizedMessage(Locale.SIMPLIFIED_CHINESE);
        assertEquals("result", "", result);
    }
    
    public void testGetMessage() throws Throwable {
        String result = new SliceMergerException("testSliceMergerExceptionMsg").getMessage();
        assertEquals("result", "testSliceMergerExceptionMsg", result);
    }
}

